# Generated by Django 4.1.3 on 2022-11-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
